package paintagm;

import sm.agm.iu.LienzoImagen2D;

/**
 * Clase VentanaInterna
 * Un objeto de esta clase representa una ventana interna, la cual contiene el lienzo
 * usado para dibujar o para mostrar imágenes.
 * @author Angel
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * VentanaPrincipal padre
     */
    private VentanaPrincipal parent;
    
    /**
     * Creates new form VentanaInterna
     * @param parent Ventana principal padre
     */
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.agm.iu.LienzoImagen2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        lienzo.setBackground(new java.awt.Color(153, 153, 153));
        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lienzoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienzoMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if (parent != null) {
            parent.deactivateTools();
            parent.repaint();
            parent.setCurrentWindow();
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseEntered
        parent.showMouseCoordinates(true);
    }//GEN-LAST:event_lienzoMouseEntered

    private void lienzoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseExited
        parent.showMouseCoordinates(false);
    }//GEN-LAST:event_lienzoMouseExited

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        parent.updateMouseCoordinatesLabel(evt.getPoint());
    }//GEN-LAST:event_lienzoMouseMoved

    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        lienzoMouseMoved(evt);
    }//GEN-LAST:event_lienzoMouseDragged

    /**
     * Devuelve el lienzo de esta ventana interna.
     * @return Lienzo de esta ventana interna.
     */
    public LienzoImagen2D getLienzo() { return this.lienzo; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.agm.iu.LienzoImagen2D lienzo;
    // End of variables declaration//GEN-END:variables
}
