package sm.agm.iu;

/**
 * Clase AboutWindow
 * Una objeto de esta clase representa un diálogo con el nombre de la aplicación,
 * desarrollador, email y versión.
 * @author Angel
 */
public class AboutWindow extends javax.swing.JDialog {

    /**
     * Creates new form AboutWindow
     * @param parent Frame padre
     * @param modal Si se quiere bloquear o no el resto de ventanas
     */
    public AboutWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Acerca de AGPaint");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        titlePanel1 = new javax.swing.JPanel();
        author = new javax.swing.JLabel();
        titlePanel2 = new javax.swing.JPanel();
        version = new javax.swing.JLabel();
        titlePanel3 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLabel.setText("AGPaint");
        titlePanel.add(titleLabel);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        imagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tools.png"))); // NOI18N
        imagePanel.add(image);

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        infoPanel.setLayout(new java.awt.BorderLayout());

        author.setText("Desarrollado por: Ángel Gómez Martín");
        titlePanel1.add(author);

        infoPanel.add(titlePanel1, java.awt.BorderLayout.CENTER);

        version.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        version.setText("v0.1");
        titlePanel2.add(version);

        infoPanel.add(titlePanel2, java.awt.BorderLayout.NORTH);

        email.setText("agomezm@correo.ugr.es");
        titlePanel3.add(email);

        infoPanel.add(titlePanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(infoPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel email;
    private javax.swing.JLabel image;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titlePanel1;
    private javax.swing.JPanel titlePanel2;
    private javax.swing.JPanel titlePanel3;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
